# Generated by Django 3.1.1 on 2020-10-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BOOKS', 'Books'), ('MUSIC', 'Music'), ('MOVIES', 'Movies'), ('GAMES', 'Games'), ('ELECTRONICS', 'Electronics'), ('KITCHEN', 'Kitchen'), ('BABY', 'Baby'), ('TRAVEL', 'Travel'), ('CLOTHING', 'Clothes'), ('ANIMALS', 'Animals'), ('SPORTS', 'Sports'), ('FOOD', 'Food')], max_length=16),
        ),
    ]
