# Generated by Django 3.1.1 on 2020-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201003_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BOOKS', 'Books'), ('MUSIC', 'Music'), ('MOVIES', 'Movies'), ('GAMES', 'Games'), ('ELECTRONICS', 'Electronics'), ('KITCHEN', 'Kitchen'), ('BABY', 'Baby'), ('TRAVEL', 'Travel'), ('CLOTHING', 'Clothes'), ('ANIMALS', 'Animals'), ('SPORTS', 'Sports'), ('FOOD', 'Food')], max_length=16),
        ),
    ]
